# Generated by Django 4.2.5 on 2024-10-28 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS', models.CharField(max_length=20, unique=True)),
                ('ps_date', models.DateField(blank=True, null=True)),
                ('SST10', models.CharField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=20, null=True)),
                ('byr_po', models.CharField(blank=True, max_length=20, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('byr', models.CharField(blank=True, max_length=50, null=True)),
                ('ship_date', models.DateField(blank=True, null=True)),
                ('cap_item', models.CharField(blank=True, max_length=20, null=True)),
                ('cap_type', models.CharField(blank=True, max_length=20, null=True)),
                ('ship_via', models.CharField(blank=True, max_length=10, null=True)),
                ('destination', models.CharField(blank=True, max_length=50, null=True)),
                ('final_destination', models.CharField(blank=True, max_length=50, null=True)),
                ('embroidery', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('washing_method', models.CharField(blank=True, max_length=50, null=True)),
                ('c_pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('v_pattern', models.CharField(blank=True, max_length=20, null=True)),
                ('eyelet_number', models.IntegerField(blank=True, null=True)),
                ('eyelet_material', models.CharField(blank=True, max_length=20, null=True)),
                ('c_cutter', models.CharField(blank=True, max_length=20, null=True)),
                ('v_cutter', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('f_mold', models.CharField(blank=True, max_length=50, null=True)),
                ('b_mold', models.CharField(blank=True, max_length=50, null=True)),
                ('visor_rows', models.IntegerField(blank=True, null=True)),
                ('extra_stitch_rows', models.IntegerField(blank=True, null=True)),
                ('first_row_from_brim', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('distance_from_front_end', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('packing', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cap_orders',
                'ordering': ['ps_date'],
            },
        ),
        migrations.CreateModel(
            name='CapOrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cap_order_images/')),
                ('cap_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='DadaApp.caporder')),
            ],
        ),
    ]
